### ISSUE TITLE
For testing is it possible to force the date, but not the time?

### ISSUE THREAD

**Issue by kd2gfn** [superlou/zenkaikon24#16]
For testing is it possible to force the date, but not the time?
This way we can see the schedule change as the time increments throughout the day we select to watch

**Comment by superlou** [comment]
Would it be more useful if when you put in the debug datetime, there is an option to let time advance from when the configuration was saved? Or is it specifically that we want to force the date but the time must be the real clock time?

**Comment by kd2gfn** [comment]
letting the time advance from when the configuration is saved is okay.
I want to see how the schedule progresses without updating the time.

**Comment by superlou** [comment]
I added an accelerate debug datetime option, which should normally be 1 for time to progress as expected in 452d925.

![image](https://github.com/superlou/zenkaikon24/assets/709695/24807973-da11-4299-811e-7d38218c46c0)

If you want to freeze the time while the debug datetime is set, just set it to 0.
Edit: I removed the ability for the acceleration option to affect real times. That seemed too dangerous. If that gets us what we need, you can close the issue.

**Comment by kd2gfn** [comment]
Appears to work well
