### ISSUE TITLE
Autograph Digital Sign Please Read

### ISSUE THREAD

**Issue by chetjasinski** [superlou/zenkaikon24#21]
Guest relations is doing something really odd in that they aren't doing long autograph sessions (well there is one 5 hour autograph session) as they first had everything else is less than 3 hours.  There are a lot of 1 and 2 hour sessions.  I can see all the changes they've made.  In any case, we don't have to move forward with any special coding.

I apologize for the time that may have already been put in on this.

I think the rotation of Guests pictures in the 1/3 section is the only challenge but will be easy enough to do since we'll also be rotating Sponsors.  All the rest of the Digital Signs will only rotate Sponsors and that will be the same on all of those.

**Comment by superlou** [comment]
When sessions are put in the autograph location, do they actually have two locations? I don't think we're showing more than the first location returned by Guidebook right now, so I'd have to add that.

**Comment by chetjasinski** [comment]
Not sure if I can make reply in email.

Location for Autographs should be "Autographs".  If you see another let me
know on what session.

**Comment by kd2gfn** [comment]
To be clear about this issue:
1 sign will be different from the rest. it will have a different setup than the other 5 signs
This will be the sign will be located in the autograph area.
The left panel will be the images of the artists signing autographs.
The right panel needs a filtered view of the "Happening now" and "Starting soon" to show only autograph sessions.
The Right panel should not show any other events for this sign.

All other signs will display all events including the autographs

I believe the tag we are looking for is : Autographs

**Comment by superlou** [comment]
I'm going to try to make it so you can specify a filtering location for TopicSessionList and TopicSessionBrief like the following:

```
!session-list
data:data_sessions_now.json
filter-location:Autographs
```

**Comment by kd2gfn** [comment]
It's not filtering, I tried with both now and soon topics. Showing
everything

**Comment by kd2gfn** [comment]
Update: needed to reboot Pi for change to take effect. Working properly.
