### ISSUE TITLE
Change session brief "closed" symbology

### ISSUE THREAD

**Issue by chetjasinski** [superlou/zenkaikon24#22]
Can closed be CLOSED and can it be made larger?

**Comment by superlou** [comment]
These are the current badges on the session brief:

![image](https://github.com/superlou/zenkaikon24/assets/709695/e475759a-2999-4009-beed-13ab6b0b5e5a)

Should they all be capitalized? That actually forces me to use a slightly smaller font to fit the text:

![image](https://github.com/superlou/zenkaikon24/assets/709695/370b5691-683d-4a04-96b6-5f0cc692dc63)

I think the color will be a pretty good indicator. The text was to help someone learn our symbology, but as soon as they know it, the color tells you at a glance.

**Comment by superlou** [comment]
After discussion, we're ok with it as is for this year. Let's see how people handle readability.
