### ISSUE TITLE
Topic device filter not working

### ISSUE THREAD

**Issue by superlou** [superlou/zenkaikon24#25]
The device filter isn't working for topics. This is forcing us to have a unique device setup for each sign. We should be able to specify a device, and when it is selected, the topic only plays on that device.

![image](https://github.com/superlou/zenkaikon24/assets/709695/84581191-651a-4e73-82f1-ecb9cc1dbf5d)

**Comment by kd2gfn** [comment]
For the filter by device serial number, I have 2 Pi's running same setup. One pi is supposed to show one image the other pi the second image. To keep it simple I only have 2 images setup.Don't know if this matters, I am trying to use filter by device on right panel as that's where the floor maps will be displayed

**Comment by superlou** [comment]
Is that not working with the device serial number specified?

**Comment by kd2gfn** [comment]
Both Pi's are showing both images, each pi should only show 1 image

**Comment by superlou** [comment]
Can you show me a screenshot of your configuration page with the topics?

**Comment by kd2gfn** [comment]
Update: Pi's had to be rebooted for change to take effect. All working
